# Generated by Django 3.2.2 on 2023-01-29 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_post_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='contact',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
