# Generated by Django 3.2.2 on 2023-01-29 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_post_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='area',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='landmarks',
            field=models.CharField(blank=True, default='', max_length=1000, null=True),
        ),
    ]
